os:
  - linux
  - osx
  - windows

language: c

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"
    - "$HOME/nim"

branches:
  except:
    - gh-pages

install:
  - |
    export CHOOSENIM_NO_ANALYTICS=1
    export CHOOSENIM_CHOOSE_VERSION=stable
    curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
    sh init.sh -y
    export PATH=$HOME/.nimble/bin:$PATH
    echo "export PATH=$HOME/.nimble/bin:$PATH" >> ~/.profile
    choosenim stable

script:
  - nimble install -y
  - nimble release

after_script:
  - fugitive --version

deploy:
  - provider: script
    script: bash .travis_release
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
